<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="pagina2.aspx.cs" Inherits="WebAppEjemplo.pagina2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    Hola desde la pagina 2<asp:Panel ID="Panel1" runat="server">
            <asp:Label ID="Label1" runat="server" Text="Nombre"></asp:Label>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="Label2" runat="server" Text="Apellido"></asp:Label>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        </asp:Panel>
&nbsp;<div>
            <asp:LinkButton PostBackUrl="~/pagina3.aspx" Text="Presióname" runat="server">Otro texto</asp:LinkButton>
            <br />
            <br />
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="btn Transfer" />
        </div>
        <asp:Panel ID="Panel2" runat="server" Width="192px">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="True" OnRowDeleting="GridView1_RowDelete" OnRowUpdating="grdview_RowUpdating" OnRowEditing="GridView1_RowEditing" AutoGenerateDeleteButton="True">
            </asp:GridView>
            <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="btnCrear" />
            <asp:Button ID="Button4" runat="server" OnClick="Button4_Click" Text="btnEditar" />
        </asp:Panel>
        <asp:Panel ID="Panel3" runat="server">
            <asp:TextBox ID="TextBox3" runat="server" ToolTip="Escriba el color"></asp:TextBox>
            <asp:TextBox ID="TextBox4" runat="server" ToolTip="Escriba el estado"></asp:TextBox>
            <asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Button" />
        </asp:Panel>
    </form>
</body>
</html>
